name: Org → README.md (with GitHub alerts)
description: Export README.org to README.md using ox-gfm (+ optional alert callouts)
author: you
branding:
  icon: book
  color: blue

inputs:
  org-path:
    description: Path to the source Org file
    default: README.org
  md-path:
    description: Output Markdown path
    default: README.md
  alerts:
    description: Convert Org special blocks to GitHub alert callouts
    default: "true"
  use-title-helper:
    description: Apply ox-md-title tweaks (Jeff’s helper)
    default: "true"
  commit:
    description: Add/commit/push the generated file
    default: "false"
  git-user-name:
    description: Git username to use when committing
    default: github-actions[bot]
  git-user-email:
    description: Git email to use when committing
    default: github-actions[bot]@users.noreply.github.com

runs:
  using: composite
  steps:
    - name: Install Emacs
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs-nox

    - name: Export Org → GFM
      shell: bash
      env:
        ORG_PATH: ${{ inputs.org-path }}
        MD_PATH: ${{ inputs.md-path }}
        ALERTS: ${{ inputs.alerts }}
        USE_TITLE_HELPER: ${{ inputs.use-title-helper }}
      run: |
        emacs -Q --batch "$ORG_PATH" \
          -l "$GITHUB_ACTION_PATH/readme.el" \
          --eval "(readme/to-markdown \"$MD_PATH\" \"$ALERTS\" \"$USE_TITLE_HELPER\")"

    - name: Commit changes (optional)
      if: inputs.commit == 'true'
      shell: bash
      run: |
        if ! git diff --quiet --exit-code ${{ inputs.md-path }}; then
          git config user.name  "${{ inputs.git-user-name }}"
          git config user.email "${{ inputs.git-user-email }}"
          git add "${{ inputs.md-path }}"
          git commit -m "chore: rebuild ${{ inputs.md-path }} from ${{ inputs.org-path }}"
          git push
        fi
