name: Org → README.md (with GitHub alerts)
description: Export README.org to README.md using ox-gfm (+ optional alert callouts)
author: Aidan Prior
branding:
  icon: book
  color: blue

inputs:
  org-path:
    description: Path to the source Org file
    default: README.org
  md-path:
    description: Output Markdown path
    default: README.md
  alerts:
    description: Convert Org special blocks to GitHub alert callouts
    default: true
  use-title-helper:
    description: Apply ox-md-title tweaks 
    default: true
  commit:
    description: Add/commit/push the generated file
    default: false
  force-amend:
    description: Amend the current commit instead of adding a new one
    default: false
  git-user-name:
    description: Git username to use when committing
    default: github-actions[bot]
  git-user-email:
    description: Git email to use when committing
    default: github-actions[bot]@users.noreply.github.com

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 2  # needed for --amend

    - uses: purcell/setup-emacs@master
      with:
        version: 28.2

    - name: Export Org → GFM
      shell: bash
      env:
        ORG_PATH: ${{ inputs.org-path }}
        MD_PATH: ${{ inputs.md-path }}
        ALERTS: ${{ inputs.alerts }}
        USE_TITLE_HELPER: ${{ inputs.use-title-helper }}
      run: |
        emacs -Q --batch "$ORG_PATH" \
          -l "$GITHUB_ACTION_PATH/readme.el" \
          --eval "(readme/to-markdown \"$MD_PATH\" \"$ALERTS\" \"$USE_TITLE_HELPER\")"

    # Capture last commit metadata (only if we will amend)
    - name: Get last commit message
      if: fromJSON(inputs.commit) && fromJSON(inputs.force-amend)
      id: last-commit
      shell: bash
      run: |
        echo "message<<EOF" >> "$GITHUB_OUTPUT"
        git log -1 --pretty=%B >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        echo "author=$(git log -1 --pretty='%an <%ae>')" >> "$GITHUB_OUTPUT"

    # Amend the current commit with README.md only
    - uses: stefanzweifel/git-auto-commit-action@v6
      if: fromJSON(inputs.commit) && fromJSON(inputs.force-amend)
      with:
        file_pattern: ${{ inputs.md-path }}
        commit_message: ${{ steps.last-commit.outputs.message }}
        commit_options: --amend --no-edit
        push_options: --force-with-lease

    # Or create a new commit
    - uses: stefanzweifel/git-auto-commit-action@v6
      if: fromJSON(inputs.commit) && !fromJSON(inputs.force-amend)
      with:
        file_pattern: ${{ inputs.md-path }}
        commit_message: "docs: Generate `${{ inputs.md-path }}` from `${{ inputs.org-path }}`"
