name: Generate README.md from README.org
on:
  push:
    branches-ignore:
      - main                      # recommended for commit: true
    paths:
      - '**/.org'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write             # only needed if commit: true
    steps:
      - uses: aidanprior/org-to-gfm-readme-md@v1
        with:
          org-path: README.org
          md-path: README.md
          alerts: true            # convert #+begin_note → [!NOTE]
          use-title-helper: true  # Jeff's title tweak
          commit: true            # auto-commit README.md
