name: Build README.md from README.org
on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/.org'
  workflow_dispatch:

permissions:
  contents: write   # only needed if commit: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          org-path: README.org
          md-path: README.md
          alerts: true           # convert #+begin_note → [!NOTE]
          use-title-helper: true # keep Jeff's title tweak
          commit: true           # auto-commit README.md
